### PR TITLE
seed data

### PR DESCRIPTION
**Pull request by funkytek**
added a script to create seed data in db so example runs properly out of the box

### CODE REVIEW

**Comment by hekike** [comment]
@funkytek why don't you do just:

```javascript

var users = [];

yield User.create(users);
process.exit(0);

```

**Comment by funkytek** [comment]
although it doesn't matter in this case, since we have docs that depend on previous docs, if we wanted to do more complex things referencing them we would need something like this.  Updating to a batch create.

**Comment by hekike** [comment]
@funkytek thanks to participating in this! :ship:

**Comment by funkytek** [comment]
:ok_hand:

**Pull request merged**
